# Generated by Django 5.0 on 2023-12-09 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxout_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laxoutuser',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 9, 17, 48, 26, 418636, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='user_uid',
            field=models.CharField(default='Q;,Gz7JutiT9/M"yC.@"AIzWrEBc*LS*?xILr4M<s~wBr*W(i\':6-:U@L2=R<7%o`Yb#qJTb$Tt2XRp|g$+U9{PT1A\\j=`~*jvv.', max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='physio',
            name='user_uid',
            field=models.CharField(default=';*>>k/E-Fy{\'g&|B!f\\"bE@FbZHr$5b3s^,BWsv9#cvnVrpz#d$`XV$"82vV&_/e]5Z>1!e}d0C6Hgns4i"S"/`YK@F\'$5LG#kxa', max_length=180, unique=True),
        ),
    ]
