# Generated by Django 5.0.2 on 2024-02-22 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laxout_app", "0002_first_second_alter_doneexercises_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LaxTree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("condition", models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="laxoutuser",
            name="email_adress",
            field=models.CharField(default="", max_length=40),
        ),
        migrations.AddField(
            model_name="laxoutuser",
            name="instruction_in_int",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="laxoutuser",
            name="lax_tree_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="laxoutuser",
            name="water_drops_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="doneexercises",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 22, 18, 31, 25, 515222)
            ),
        ),
        migrations.AlterField(
            model_name="doneworkouts",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 22, 18, 31, 25, 514662)
            ),
        ),
        migrations.AlterField(
            model_name="indexesphysios",
            name="for_week",
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name="laxoutuser",
            name="creation_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 2, 22, 18, 31, 25, 519216, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="laxoutuser",
            name="last_meet",
            field=models.DateField(
                default=datetime.datetime(2024, 2, 22, 18, 31, 25, 519389)
            ),
        ),
        migrations.AlterField(
            model_name="laxoutuserindexcreationlog",
            name="for_week",
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name="laxoutuserpains",
            name="for_week",
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name="physioindexcreationlog",
            name="for_week",
            field=models.IntegerField(default=8),
        ),
    ]
