# Generated by Django 5.0.7 on 2024-07-21 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxout_app', '0002_exerciseid_alter_aktivebeweglichkeit_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finetuningtrainingdata',
            name='created_for',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aktivebeweglichkeit',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 10, 5, 18, 347033)),
        ),
        migrations.AlterField(
            model_name='alltagsfunktionen',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 10, 5, 18, 350034)),
        ),
        migrations.AlterField(
            model_name='apleyzeichen',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 10, 5, 18, 357036)),
        ),
        migrations.AlterField(
            model_name='aprehensiontest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 10, 5, 18, 353035)),
        ),
        migrations.AlterField(
            model_name='beinlaengenmessung',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 10, 5, 18, 351034)),
        ),
        migrations.AlterField(
            model_name='beweglichkeitsmessungknie',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 10, 5, 18, 349034)),
        ),
        migrations.AlterField(
            model_name='dokumentation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 21, 8, 5, 18, 375040, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='doneexercises',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 21, 10, 5, 18, 325030)),
        ),
        migrations.AlterField(
            model_name='doneworkouts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 21, 10, 5, 18, 325029)),
        ),
        migrations.AlterField(
            model_name='einbeinstand30sekundengeschlosseneaugen',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 10, 5, 18, 350034)),
        ),
        migrations.AlterField(
            model_name='einbeinstand60sekunden',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 10, 5, 18, 350034)),
        ),
        migrations.AlterField(
            model_name='facettendruckschmerztest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 10, 5, 18, 354035)),
        ),
        migrations.AlterField(
            model_name='fragenevaluationennachdembiopsychosozialenkrankheitsmodell',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 10, 5, 18, 345033)),
        ),
        migrations.AlterField(
            model_name='fragenevaluationennachden7wfragen',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 10, 5, 18, 345033)),
        ),
        migrations.AlterField(
            model_name='fragenevaluationnachicfkategorien',
            name='created_at_icf',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 10, 5, 18, 344033)),
        ),
        migrations.AlterField(
            model_name='glidetest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 10, 5, 18, 352035)),
        ),
        migrations.AlterField(
            model_name='gravitiysign',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 10, 5, 18, 355035)),
        ),
        migrations.AlterField(
            model_name='hamstringtest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 10, 5, 18, 351034)),
        ),
        migrations.AlterField(
            model_name='hintereschublade',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 10, 5, 18, 355035)),
        ),
        migrations.AlterField(
            model_name='historiamorbis',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 10, 5, 18, 346033)),
        ),
        migrations.AlterField(
            model_name='hughstonplicatest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 10, 5, 18, 358036)),
        ),
        migrations.AlterField(
            model_name='isometrischerkrafttest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 10, 5, 18, 349034)),
        ),
        migrations.AlterField(
            model_name='lachmanntest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 10, 5, 18, 354035)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 8, 5, 18, 328029, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='last_meet',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 10, 5, 18, 328029)),
        ),
        migrations.AlterField(
            model_name='loomerstest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 10, 5, 18, 356035)),
        ),
        migrations.AlterField(
            model_name='macmurraytest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 10, 5, 18, 357036)),
        ),
        migrations.AlterField(
            model_name='mediopatellarerplicatest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 10, 5, 18, 358036)),
        ),
        migrations.AlterField(
            model_name='miniergusstest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 10, 5, 18, 352035)),
        ),
        migrations.AlterField(
            model_name='mrectusdehnungstest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 10, 5, 18, 351034)),
        ),
        migrations.AlterField(
            model_name='muskelfunktionspruefung',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 10, 5, 18, 349034)),
        ),
        migrations.AlterField(
            model_name='nebenerkrankungenmedikamente',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 10, 5, 18, 346033)),
        ),
        migrations.AlterField(
            model_name='nrsnumericratingscale',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 10, 5, 18, 347033)),
        ),
        migrations.AlterField(
            model_name='passivebeweglichkeit',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 10, 5, 18, 348033)),
        ),
        migrations.AlterField(
            model_name='payrzeichen',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 10, 5, 18, 357036)),
        ),
        migrations.AlterField(
            model_name='pivotshifttest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 10, 5, 18, 355035)),
        ),
        migrations.AlterField(
            model_name='quadricepsdehnungstest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 10, 5, 18, 351034)),
        ),
        migrations.AlterField(
            model_name='standartbefund',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 10, 5, 18, 347033)),
        ),
        migrations.AlterField(
            model_name='standderrehaphase',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 10, 5, 18, 345033)),
        ),
        migrations.AlterField(
            model_name='steinmann1',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 10, 5, 18, 356035)),
        ),
        migrations.AlterField(
            model_name='steinmann3',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 10, 5, 18, 356035)),
        ),
        migrations.AlterField(
            model_name='tanzendepatella',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 10, 5, 18, 352035)),
        ),
        migrations.AlterField(
            model_name='theslaytest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 10, 5, 18, 356035)),
        ),
        migrations.AlterField(
            model_name='tilttest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 10, 5, 18, 353035)),
        ),
        migrations.AlterField(
            model_name='umfangsmessung',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 10, 5, 18, 352035)),
        ),
        migrations.AlterField(
            model_name='valgustest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 10, 5, 18, 354035)),
        ),
        migrations.AlterField(
            model_name='varustest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 10, 5, 18, 354035)),
        ),
        migrations.AlterField(
            model_name='vordereschublade',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 10, 5, 18, 355035)),
        ),
        migrations.AlterField(
            model_name='zohlenzeichen',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 10, 5, 18, 353035)),
        ),
    ]
