# Generated by Django 5.0 on 2023-12-09 22:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxout_app', '0002_alter_laxoutuser_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laxoutuser',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 9, 22, 46, 20, 893747, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='user_uid',
            field=models.CharField(default='i>=aJv\\#dKXV{0+iAhVQ1)kC1~Fa6BWgGdA>f/A;HERk~0orw_I16n=x1x>g%0"ld:Yldl_S:czc8znkEM_>.A/im}v&"rlH#3FD', max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='physio',
            name='user_uid',
            field=models.CharField(default='1uh}a#}oZ?"S)Uj8EXNl+Y2|Fi0oWBllsz8-+Eu9S^OoIwP<bWd~E?m6cuB=N2H8xURt|04Uu74aY<5cOno5Rj~r_jK1qfPWG;Q:', max_length=180, unique=True),
        ),
    ]
