# Generated by Django 5.0 on 2023-12-09 22:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxout_app', '0003_alter_laxoutuser_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laxoutuser',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 9, 22, 57, 47, 99072, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='user_uid',
            field=models.CharField(default='"UUSf~>JD)&s`m<LS>L+fH}ge|=`b\\r%&E)5NIL$Jue-:sj#a9d[O+].$a+j=\'Bp6yU)mvC@;rh>C:i0>^ts_YO&iUjxa&Sx:ts5', max_length=180, unique=True),
        ),
        migrations.DeleteModel(
            name='Physio',
        ),
    ]
