# Generated by Django 5.0.7 on 2024-07-21 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxout_app', '0004_alter_aktivebeweglichkeit_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktivebeweglichkeit',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 11, 15, 56, 425359)),
        ),
        migrations.AlterField(
            model_name='alltagsfunktionen',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 11, 15, 56, 428360)),
        ),
        migrations.AlterField(
            model_name='apleyzeichen',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 11, 15, 56, 436362)),
        ),
        migrations.AlterField(
            model_name='aprehensiontest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 11, 15, 56, 432361)),
        ),
        migrations.AlterField(
            model_name='beinlaengenmessung',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 11, 15, 56, 429360)),
        ),
        migrations.AlterField(
            model_name='beweglichkeitsmessungknie',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 11, 15, 56, 427360)),
        ),
        migrations.AlterField(
            model_name='dokumentation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 21, 9, 15, 56, 454365, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='doneexercises',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 21, 11, 15, 56, 405355)),
        ),
        migrations.AlterField(
            model_name='doneworkouts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 21, 11, 15, 56, 405354)),
        ),
        migrations.AlterField(
            model_name='einbeinstand30sekundengeschlosseneaugen',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 11, 15, 56, 428360)),
        ),
        migrations.AlterField(
            model_name='einbeinstand60sekunden',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 11, 15, 56, 428360)),
        ),
        migrations.AlterField(
            model_name='facettendruckschmerztest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 11, 15, 56, 432361)),
        ),
        migrations.AlterField(
            model_name='fragenevaluationennachdembiopsychosozialenkrankheitsmodell',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 11, 15, 56, 413357)),
        ),
        migrations.AlterField(
            model_name='fragenevaluationennachden7wfragen',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 11, 15, 56, 413357)),
        ),
        migrations.AlterField(
            model_name='fragenevaluationnachicfkategorien',
            name='created_at_icf',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 11, 15, 56, 413357)),
        ),
        migrations.AlterField(
            model_name='glidetest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 11, 15, 56, 431362)),
        ),
        migrations.AlterField(
            model_name='gravitiysign',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 11, 15, 56, 434361)),
        ),
        migrations.AlterField(
            model_name='hamstringtest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 11, 15, 56, 430360)),
        ),
        migrations.AlterField(
            model_name='hintereschublade',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 11, 15, 56, 434361)),
        ),
        migrations.AlterField(
            model_name='historiamorbis',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 11, 15, 56, 416357)),
        ),
        migrations.AlterField(
            model_name='hughstonplicatest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 11, 15, 56, 437362)),
        ),
        migrations.AlterField(
            model_name='isometrischerkrafttest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 11, 15, 56, 427360)),
        ),
        migrations.AlterField(
            model_name='lachmanntest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 11, 15, 56, 433361)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 9, 15, 56, 407355, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='last_meet',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 11, 15, 56, 408355)),
        ),
        migrations.AlterField(
            model_name='loomerstest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 11, 15, 56, 434361)),
        ),
        migrations.AlterField(
            model_name='macmurraytest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 11, 15, 56, 436362)),
        ),
        migrations.AlterField(
            model_name='mediopatellarerplicatest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 11, 15, 56, 436362)),
        ),
        migrations.AlterField(
            model_name='miniergusstest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 11, 15, 56, 431362)),
        ),
        migrations.AlterField(
            model_name='mrectusdehnungstest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 11, 15, 56, 429360)),
        ),
        migrations.AlterField(
            model_name='muskelfunktionspruefung',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 11, 15, 56, 428360)),
        ),
        migrations.AlterField(
            model_name='nebenerkrankungenmedikamente',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 11, 15, 56, 415359)),
        ),
        migrations.AlterField(
            model_name='nrsnumericratingscale',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 11, 15, 56, 417358)),
        ),
        migrations.AlterField(
            model_name='passivebeweglichkeit',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 11, 15, 56, 426360)),
        ),
        migrations.AlterField(
            model_name='payrzeichen',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 11, 15, 56, 436362)),
        ),
        migrations.AlterField(
            model_name='pivotshifttest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 11, 15, 56, 434361)),
        ),
        migrations.AlterField(
            model_name='quadricepsdehnungstest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 11, 15, 56, 429360)),
        ),
        migrations.AlterField(
            model_name='standartbefund',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 11, 15, 56, 416357)),
        ),
        migrations.AlterField(
            model_name='standderrehaphase',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 11, 15, 56, 415359)),
        ),
        migrations.AlterField(
            model_name='steinmann1',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 11, 15, 56, 435361)),
        ),
        migrations.AlterField(
            model_name='steinmann3',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 11, 15, 56, 435361)),
        ),
        migrations.AlterField(
            model_name='tanzendepatella',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 11, 15, 56, 431362)),
        ),
        migrations.AlterField(
            model_name='theslaytest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 11, 15, 56, 435361)),
        ),
        migrations.AlterField(
            model_name='tilttest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 11, 15, 56, 431362)),
        ),
        migrations.AlterField(
            model_name='umfangsmessung',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 11, 15, 56, 430360)),
        ),
        migrations.AlterField(
            model_name='valgustest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 11, 15, 56, 433361)),
        ),
        migrations.AlterField(
            model_name='varustest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 11, 15, 56, 433361)),
        ),
        migrations.AlterField(
            model_name='vordereschublade',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 11, 15, 56, 433361)),
        ),
        migrations.AlterField(
            model_name='zohlenzeichen',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 11, 15, 56, 432361)),
        ),
        migrations.CreateModel(
            name='AiContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_for', models.IntegerField(default=0)),
                ('plan_name', models.CharField(default='', max_length=300)),
                ('plan_info', models.CharField(default='', max_length=3000)),
                ('related_exercise_ids', models.ManyToManyField(to='laxout_app.exerciseid')),
            ],
        ),
    ]
