# Generated by Django 5.0 on 2023-12-09 22:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxout_app', '0004_alter_laxoutuser_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laxoutuser',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 9, 22, 58, 11, 84210, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='user_uid',
            field=models.CharField(default="{LY|Ybz*dK?WSYbxI%&3>x6W(p/s;2dkE2YbM8xX1|paE!1a;-/Dz7|q59ev-=AZirqS:JrL$n(mq%>Xt?eI!F,rX_+aZ-jw,n'p", max_length=180, unique=True),
        ),
    ]
