# Generated by Django 5.0 on 2023-12-10 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxout_app', '0005_alter_laxoutuser_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laxoutuser',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 10, 16, 33, 21, 812013, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='user_uid',
            field=models.CharField(default='G9e2DtRJeMEShrN2Z35m2Ry4vnEuGRtcDx2GIkr4Wx4ARuKjCqSRRuKD9BDloRZHhmXyOL', max_length=420, unique=True),
        ),
    ]
