# Generated by Django 5.0.7 on 2024-07-22 19:06

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxout_app', '0005_alter_aktivebeweglichkeit_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktivebeweglichkeit',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 21, 6, 41, 204803)),
        ),
        migrations.AlterField(
            model_name='alltagsfunktionen',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 21, 6, 41, 206803)),
        ),
        migrations.AlterField(
            model_name='apleyzeichen',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 21, 6, 41, 214805)),
        ),
        migrations.AlterField(
            model_name='aprehensiontest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 21, 6, 41, 209804)),
        ),
        migrations.AlterField(
            model_name='beinlaengenmessung',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 21, 6, 41, 207803)),
        ),
        migrations.AlterField(
            model_name='beweglichkeitsmessungknie',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 21, 6, 41, 205803)),
        ),
        migrations.AlterField(
            model_name='dokumentation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 22, 19, 6, 41, 233809, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='doneexercises',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 22, 21, 6, 41, 184798)),
        ),
        migrations.AlterField(
            model_name='doneworkouts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 22, 21, 6, 41, 184798)),
        ),
        migrations.AlterField(
            model_name='einbeinstand30sekundengeschlosseneaugen',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 21, 6, 41, 206803)),
        ),
        migrations.AlterField(
            model_name='einbeinstand60sekunden',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 21, 6, 41, 206803)),
        ),
        migrations.AlterField(
            model_name='facettendruckschmerztest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 21, 6, 41, 210804)),
        ),
        migrations.AlterField(
            model_name='fragenevaluationennachdembiopsychosozialenkrankheitsmodell',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 21, 6, 41, 192800)),
        ),
        migrations.AlterField(
            model_name='fragenevaluationennachden7wfragen',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 21, 6, 41, 193800)),
        ),
        migrations.AlterField(
            model_name='fragenevaluationnachicfkategorien',
            name='created_at_icf',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 21, 6, 41, 192800)),
        ),
        migrations.AlterField(
            model_name='glidetest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 21, 6, 41, 209804)),
        ),
        migrations.AlterField(
            model_name='gravitiysign',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 21, 6, 41, 212805)),
        ),
        migrations.AlterField(
            model_name='hamstringtest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 21, 6, 41, 208804)),
        ),
        migrations.AlterField(
            model_name='hintereschublade',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 21, 6, 41, 211805)),
        ),
        migrations.AlterField(
            model_name='historiamorbis',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 21, 6, 41, 194801)),
        ),
        migrations.AlterField(
            model_name='hughstonplicatest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 21, 6, 41, 214805)),
        ),
        migrations.AlterField(
            model_name='indexesphysios',
            name='for_week',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='isometrischerkrafttest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 21, 6, 41, 205803)),
        ),
        migrations.AlterField(
            model_name='lachmanntest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 21, 6, 41, 211805)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 19, 6, 41, 187799, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='last_meet',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 21, 6, 41, 187799)),
        ),
        migrations.AlterField(
            model_name='laxoutuserindexcreationlog',
            name='for_week',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='laxoutuserpains',
            name='for_week',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='loomerstest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 21, 6, 41, 212805)),
        ),
        migrations.AlterField(
            model_name='macmurraytest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 21, 6, 41, 213805)),
        ),
        migrations.AlterField(
            model_name='mediopatellarerplicatest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 21, 6, 41, 214805)),
        ),
        migrations.AlterField(
            model_name='miniergusstest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 21, 6, 41, 209804)),
        ),
        migrations.AlterField(
            model_name='mrectusdehnungstest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 21, 6, 41, 207803)),
        ),
        migrations.AlterField(
            model_name='muskelfunktionspruefung',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 21, 6, 41, 206803)),
        ),
        migrations.AlterField(
            model_name='nebenerkrankungenmedikamente',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 21, 6, 41, 193800)),
        ),
        migrations.AlterField(
            model_name='nrsnumericratingscale',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 21, 6, 41, 203802)),
        ),
        migrations.AlterField(
            model_name='passivebeweglichkeit',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 21, 6, 41, 204803)),
        ),
        migrations.AlterField(
            model_name='payrzeichen',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 21, 6, 41, 213805)),
        ),
        migrations.AlterField(
            model_name='physioindexcreationlog',
            name='for_week',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='pivotshifttest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 21, 6, 41, 211805)),
        ),
        migrations.AlterField(
            model_name='quadricepsdehnungstest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 21, 6, 41, 207803)),
        ),
        migrations.AlterField(
            model_name='standartbefund',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 21, 6, 41, 194801)),
        ),
        migrations.AlterField(
            model_name='standderrehaphase',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 21, 6, 41, 193800)),
        ),
        migrations.AlterField(
            model_name='steinmann1',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 21, 6, 41, 212805)),
        ),
        migrations.AlterField(
            model_name='steinmann3',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 21, 6, 41, 213805)),
        ),
        migrations.AlterField(
            model_name='tanzendepatella',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 21, 6, 41, 208804)),
        ),
        migrations.AlterField(
            model_name='theslaytest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 21, 6, 41, 213805)),
        ),
        migrations.AlterField(
            model_name='tilttest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 21, 6, 41, 209804)),
        ),
        migrations.AlterField(
            model_name='umfangsmessung',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 21, 6, 41, 208804)),
        ),
        migrations.AlterField(
            model_name='valgustest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 21, 6, 41, 210804)),
        ),
        migrations.AlterField(
            model_name='varustest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 21, 6, 41, 210804)),
        ),
        migrations.AlterField(
            model_name='vordereschublade',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 21, 6, 41, 211805)),
        ),
        migrations.AlterField(
            model_name='zohlenzeichen',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 22, 21, 6, 41, 210804)),
        ),
        migrations.CreateModel(
            name='AnalogerPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('exercises', models.ManyToManyField(to='laxout_app.laxout_exercise')),
            ],
        ),
    ]
