# Generated by Django 5.0.2 on 2024-02-23 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "laxout_app",
            "0006_alter_doneexercises_date_alter_doneworkouts_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="doneexercises",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 23, 14, 38, 58, 771105)
            ),
        ),
        migrations.AlterField(
            model_name="doneworkouts",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 23, 14, 38, 58, 770669)
            ),
        ),
        migrations.AlterField(
            model_name="laxoutuser",
            name="creation_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 2, 23, 14, 38, 58, 776650, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="laxoutuser",
            name="last_meet",
            field=models.DateField(
                default=datetime.datetime(2024, 2, 23, 14, 38, 58, 776839)
            ),
        ),
    ]
