# Generated by Django 5.0 on 2023-12-10 22:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxout_app', '0007_alter_laxoutuser_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laxoutuser',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 10, 22, 8, 0, 96762, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='user_uid',
            field=models.CharField(default='PyuCEdE9gIbZ8GKz8GLSU0H5Tkdd90s1QdQ1z66XTGWgSCyxoF3BDfuzVm4W5uO9RKT0Uf', max_length=420, unique=True),
        ),
    ]
