# Generated by Django 5.0.2 on 2024-02-25 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "laxout_app",
            "0008_alter_doneexercises_date_alter_doneworkouts_date_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SuccessControll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("better", models.BooleanField(default=False)),
                ("created_by", models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name="doneexercises",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 25, 14, 19, 38, 560306)
            ),
        ),
        migrations.AlterField(
            model_name="doneworkouts",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 25, 14, 19, 38, 559799)
            ),
        ),
        migrations.AlterField(
            model_name="laxoutuser",
            name="creation_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 2, 25, 14, 19, 38, 565653, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="laxoutuser",
            name="last_meet",
            field=models.DateField(
                default=datetime.datetime(2024, 2, 25, 14, 19, 38, 565816)
            ),
        ),
    ]
