# Generated by Django 5.0.2 on 2024-03-02 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laxout_app", "0009_successcontroll_alter_doneexercises_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doneexercises",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 3, 2, 10, 32, 23, 195897)
            ),
        ),
        migrations.AlterField(
            model_name="doneworkouts",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 3, 2, 10, 32, 23, 195515)
            ),
        ),
        migrations.AlterField(
            model_name="indexeslaxoutuser",
            name="creation_date",
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="indexesphysios",
            name="for_month",
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="indexesphysios",
            name="for_week",
            field=models.IntegerField(default=9),
        ),
        migrations.AlterField(
            model_name="laxoutuser",
            name="creation_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 3, 2, 10, 32, 23, 199661, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="laxoutuser",
            name="last_meet",
            field=models.DateField(
                default=datetime.datetime(2024, 3, 2, 10, 32, 23, 199824)
            ),
        ),
        migrations.AlterField(
            model_name="laxoutuserindexcreationlog",
            name="for_month",
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="laxoutuserindexcreationlog",
            name="for_week",
            field=models.IntegerField(default=9),
        ),
        migrations.AlterField(
            model_name="laxoutuserpains",
            name="for_month",
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="laxoutuserpains",
            name="for_week",
            field=models.IntegerField(default=9),
        ),
        migrations.AlterField(
            model_name="physioindexcreationlog",
            name="for_month",
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="physioindexcreationlog",
            name="for_week",
            field=models.IntegerField(default=9),
        ),
    ]
