# Generated by Django 5.0 on 2023-12-10 23:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxout_app', '0009_alter_laxoutuser_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laxoutuser',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 10, 23, 20, 5, 184764, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='user_uid',
            field=models.CharField(default='2fdf554a-aa66-45b4-91a1-1f37efe99436', max_length=420, unique=True),
        ),
    ]
