# Generated by Django 5.0 on 2023-12-12 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxout_app', '0010_alter_laxoutuser_creation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='physios_exercises',
        ),
        migrations.AddField(
            model_name='laxout_exercise',
            name='appId',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 12, 17, 15, 13, 476243, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='user_uid',
            field=models.CharField(default='53364878-5f3d-4f8e-97f4-49baa0dc8bde', max_length=420, unique=True),
        ),
    ]
