# Generated by Django 5.0.2 on 2024-03-31 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laxout_app", "0011_aiexercise_alter_doneexercises_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatDataModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_sender", models.BooleanField(default=False)),
                ("message", models.CharField(default="", max_length=2003000000)),
                ("created_by", models.IntegerField(default=0)),
                ("admin_id", models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="laxoutuser",
            name="admin_has_seen_chat",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="laxoutuser",
            name="user_has_seen_chat",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="doneexercises",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 3, 31, 9, 45, 41, 238662)
            ),
        ),
        migrations.AlterField(
            model_name="doneworkouts",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 3, 31, 9, 45, 41, 238174)
            ),
        ),
        migrations.AlterField(
            model_name="indexesphysios",
            name="for_week",
            field=models.IntegerField(default=13),
        ),
        migrations.AlterField(
            model_name="laxout_exercise",
            name="execution",
            field=models.CharField(default="", max_length=10000),
        ),
        migrations.AlterField(
            model_name="laxoutuser",
            name="creation_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 3, 31, 9, 45, 41, 243241, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="laxoutuser",
            name="last_meet",
            field=models.DateField(
                default=datetime.datetime(2024, 3, 31, 9, 45, 41, 243421)
            ),
        ),
        migrations.AlterField(
            model_name="laxoutuserindexcreationlog",
            name="for_week",
            field=models.IntegerField(default=13),
        ),
        migrations.AlterField(
            model_name="laxoutuserpains",
            name="for_week",
            field=models.IntegerField(default=13),
        ),
        migrations.AlterField(
            model_name="physioindexcreationlog",
            name="for_week",
            field=models.IntegerField(default=13),
        ),
        migrations.AlterField(
            model_name="uebungen_models",
            name="execution",
            field=models.CharField(default="", max_length=10000),
        ),
    ]
