# Generated by Django 5.0 on 2023-12-13 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxout_app', '0012_indexeslaxoutuser_indexesphysios_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_name', models.CharField(default='', max_length=200)),
                ('coupon_text', models.CharField(default='', max_length=400)),
                ('coupon_image_url', models.CharField(default='', max_length=200)),
                ('coupon_price', models.IntegerField(default=0)),
                ('coupon_offer', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='indexeslaxoutuser',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 13, 13, 37, 22, 365631, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='indexesphysios',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 13, 13, 37, 22, 365631, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 13, 13, 37, 22, 366632, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='user_uid',
            field=models.CharField(default='ac20be50-a965-4bb1-9aef-a13104f3b2be', max_length=420, unique=True),
        ),
    ]
