# Generated by Django 5.0.2 on 2024-04-20 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laxout_app", "0013_billingcount_alter_doneexercises_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="laxoutuser",
            name="was_created_through_app",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="doneexercises",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 20, 14, 45, 58, 166547)
            ),
        ),
        migrations.AlterField(
            model_name="doneworkouts",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 20, 14, 45, 58, 166079)
            ),
        ),
        migrations.AlterField(
            model_name="indexesphysios",
            name="for_week",
            field=models.IntegerField(default=16),
        ),
        migrations.AlterField(
            model_name="laxoutuser",
            name="creation_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 4, 20, 14, 45, 58, 170820, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="laxoutuser",
            name="last_meet",
            field=models.DateField(
                default=datetime.datetime(2024, 4, 20, 14, 45, 58, 171007)
            ),
        ),
        migrations.AlterField(
            model_name="laxoutuser",
            name="user_has_seen_chat",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="laxoutuserindexcreationlog",
            name="for_week",
            field=models.IntegerField(default=16),
        ),
        migrations.AlterField(
            model_name="laxoutuserpains",
            name="for_week",
            field=models.IntegerField(default=16),
        ),
        migrations.AlterField(
            model_name="physioindexcreationlog",
            name="for_week",
            field=models.IntegerField(default=16),
        ),
    ]
