# Generated by Django 5.0 on 2023-12-15 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxout_app', '0013_coupon_alter_indexeslaxoutuser_creation_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paint_amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='coupon',
            name='rabbat_code',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='laxoutuser',
            name='coupons',
            field=models.ManyToManyField(to='laxout_app.coupon'),
        ),
        migrations.AddField(
            model_name='laxoutuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 0, 0)),
        ),
        migrations.AlterField(
            model_name='indexeslaxoutuser',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 15, 15, 33, 38, 454546, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='indexesphysios',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 15, 15, 33, 38, 454546, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 15, 15, 33, 38, 455546, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='user_uid',
            field=models.CharField(default='e720f0c7-256c-43f7-bd02-c95218cead95', max_length=420, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='average_pain',
            field=models.ManyToManyField(to='laxout_app.pains'),
        ),
    ]
