# Generated by Django 5.0 on 2023-12-16 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxout_app', '0014_pains_coupon_rabbat_code_laxoutuser_coupons_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoneExercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_id', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=datetime.datetime.today)),
            ],
        ),
        migrations.AddField(
            model_name='laxout_exercise',
            name='skipped',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='indexeslaxoutuser',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 16, 8, 30, 16, 410369, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='indexesphysios',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 16, 8, 30, 16, 410369, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 16, 8, 30, 16, 411369, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='user_uid',
            field=models.CharField(default='0278b7d1-cc82-46d8-8c3d-d34d914c2c2d', max_length=420, unique=True),
        ),
    ]
