# Generated by Django 5.0.7 on 2024-07-26 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxout_app', '0015_anamnesechat_uid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnamneseMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='', max_length=12000)),
                ('bot_message', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='anamnesechat',
            name='bot_message',
        ),
        migrations.RemoveField(
            model_name='anamnesechat',
            name='message',
        ),
        migrations.AlterField(
            model_name='aktivebeweglichkeit',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 26, 14, 20, 27, 618200)),
        ),
        migrations.AlterField(
            model_name='alltagsfunktionen',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 26, 14, 20, 27, 621201)),
        ),
        migrations.AlterField(
            model_name='apleyzeichen',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 26, 14, 20, 27, 628203)),
        ),
        migrations.AlterField(
            model_name='aprehensiontest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 26, 14, 20, 27, 624202)),
        ),
        migrations.AlterField(
            model_name='beinlaengenmessung',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 26, 14, 20, 27, 621201)),
        ),
        migrations.AlterField(
            model_name='beweglichkeitsmessungknie',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 26, 14, 20, 27, 619200)),
        ),
        migrations.AlterField(
            model_name='dokumentation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 26, 12, 20, 27, 646205, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='doneexercises',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 26, 14, 20, 27, 599197)),
        ),
        migrations.AlterField(
            model_name='doneworkouts',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 26, 14, 20, 27, 598196)),
        ),
        migrations.AlterField(
            model_name='einbeinstand30sekundengeschlosseneaugen',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 26, 14, 20, 27, 621201)),
        ),
        migrations.AlterField(
            model_name='einbeinstand60sekunden',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 26, 14, 20, 27, 620200)),
        ),
        migrations.AlterField(
            model_name='facettendruckschmerztest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 26, 14, 20, 27, 624202)),
        ),
        migrations.AlterField(
            model_name='fragenevaluationennachdembiopsychosozialenkrankheitsmodell',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 26, 14, 20, 27, 615199)),
        ),
        migrations.AlterField(
            model_name='fragenevaluationennachden7wfragen',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 26, 14, 20, 27, 616199)),
        ),
        migrations.AlterField(
            model_name='fragenevaluationnachicfkategorien',
            name='created_at_icf',
            field=models.DateField(default=datetime.datetime(2024, 7, 26, 14, 20, 27, 615199)),
        ),
        migrations.AlterField(
            model_name='glidetest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 26, 14, 20, 27, 623201)),
        ),
        migrations.AlterField(
            model_name='gravitiysign',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 26, 14, 20, 27, 626202)),
        ),
        migrations.AlterField(
            model_name='hamstringtest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 26, 14, 20, 27, 622201)),
        ),
        migrations.AlterField(
            model_name='hintereschublade',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 26, 14, 20, 27, 626202)),
        ),
        migrations.AlterField(
            model_name='historiamorbis',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 26, 14, 20, 27, 617200)),
        ),
        migrations.AlterField(
            model_name='hughstonplicatest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 26, 14, 20, 27, 628203)),
        ),
        migrations.AlterField(
            model_name='isometrischerkrafttest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 26, 14, 20, 27, 620200)),
        ),
        migrations.AlterField(
            model_name='lachmanntest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 26, 14, 20, 27, 625202)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 26, 12, 20, 27, 601196, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='last_meet',
            field=models.DateField(default=datetime.datetime(2024, 7, 26, 14, 20, 27, 601196)),
        ),
        migrations.AlterField(
            model_name='loomerstest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 26, 14, 20, 27, 626202)),
        ),
        migrations.AlterField(
            model_name='macmurraytest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 26, 14, 20, 27, 627202)),
        ),
        migrations.AlterField(
            model_name='mediopatellarerplicatest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 26, 14, 20, 27, 628203)),
        ),
        migrations.AlterField(
            model_name='miniergusstest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 26, 14, 20, 27, 623201)),
        ),
        migrations.AlterField(
            model_name='mrectusdehnungstest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 26, 14, 20, 27, 622201)),
        ),
        migrations.AlterField(
            model_name='muskelfunktionspruefung',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 26, 14, 20, 27, 620200)),
        ),
        migrations.AlterField(
            model_name='nebenerkrankungenmedikamente',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 26, 14, 20, 27, 616199)),
        ),
        migrations.AlterField(
            model_name='nrsnumericratingscale',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 26, 14, 20, 27, 618200)),
        ),
        migrations.AlterField(
            model_name='passivebeweglichkeit',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 26, 14, 20, 27, 619200)),
        ),
        migrations.AlterField(
            model_name='payrzeichen',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 26, 14, 20, 27, 628203)),
        ),
        migrations.AlterField(
            model_name='pivotshifttest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 26, 14, 20, 27, 625202)),
        ),
        migrations.AlterField(
            model_name='quadricepsdehnungstest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 26, 14, 20, 27, 621201)),
        ),
        migrations.AlterField(
            model_name='standartbefund',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 26, 14, 20, 27, 617200)),
        ),
        migrations.AlterField(
            model_name='standderrehaphase',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 26, 14, 20, 27, 616199)),
        ),
        migrations.AlterField(
            model_name='steinmann1',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 26, 14, 20, 27, 627202)),
        ),
        migrations.AlterField(
            model_name='steinmann3',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 26, 14, 20, 27, 627202)),
        ),
        migrations.AlterField(
            model_name='tanzendepatella',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 26, 14, 20, 27, 623201)),
        ),
        migrations.AlterField(
            model_name='theslaytest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 26, 14, 20, 27, 627202)),
        ),
        migrations.AlterField(
            model_name='tilttest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 26, 14, 20, 27, 623201)),
        ),
        migrations.AlterField(
            model_name='umfangsmessung',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 26, 14, 20, 27, 622201)),
        ),
        migrations.AlterField(
            model_name='valgustest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 26, 14, 20, 27, 624202)),
        ),
        migrations.AlterField(
            model_name='varustest',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 26, 14, 20, 27, 625202)),
        ),
        migrations.AlterField(
            model_name='vordereschublade',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 26, 14, 20, 27, 625202)),
        ),
        migrations.AlterField(
            model_name='zohlenzeichen',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 26, 14, 20, 27, 624202)),
        ),
        migrations.AddField(
            model_name='anamnesechat',
            name='messages',
            field=models.ManyToManyField(to='laxout_app.anamnesemessage'),
        ),
    ]
