# Generated by Django 5.0.2 on 2024-04-25 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "laxout_app",
            "0015_alter_doneexercises_date_alter_doneworkouts_date_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SovendusCustomerUid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(default="", max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name="doneexercises",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 25, 16, 19, 47, 595551)
            ),
        ),
        migrations.AlterField(
            model_name="doneworkouts",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 25, 16, 19, 47, 595062)
            ),
        ),
        migrations.AlterField(
            model_name="laxoutuser",
            name="creation_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 4, 25, 16, 19, 47, 599756, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="laxoutuser",
            name="last_meet",
            field=models.DateField(
                default=datetime.datetime(2024, 4, 25, 16, 19, 47, 599966)
            ),
        ),
    ]
