# Generated by Django 5.0 on 2023-12-16 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxout_app', '0015_doneexercises_laxout_exercise_skipped_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doneexercises',
            name='laxout_user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='indexeslaxoutuser',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 16, 8, 31, 11, 885688, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='indexesphysios',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 16, 8, 31, 11, 885688, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 16, 8, 31, 11, 886689, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='user_uid',
            field=models.CharField(default='eca0f868-685e-4f2b-9ea9-dadebb779556', max_length=420, unique=True),
        ),
    ]
