# Generated by Django 5.0 on 2023-12-16 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxout_app', '0016_doneexercises_laxout_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkippedExercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skipped_exercise_id', models.IntegerField(default=0)),
                ('laxout_user_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='laxout_exercise',
            name='skipped',
        ),
        migrations.AlterField(
            model_name='indexeslaxoutuser',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 16, 8, 55, 9, 174546, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='indexesphysios',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 16, 8, 55, 9, 175547, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 16, 8, 55, 9, 176548, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='user_uid',
            field=models.CharField(default='6ce7fd88-f84e-4af8-8b55-4bb1055d8ed4', max_length=420, unique=True),
        ),
    ]
