# Generated by Django 5.0 on 2023-12-16 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxout_app', '0017_skippedexercises_remove_laxout_exercise_skipped_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoneWorkouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_id', models.IntegerField(default=0)),
                ('laxout_user_id', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=datetime.datetime.today)),
            ],
        ),
        migrations.AddField(
            model_name='laxoutuser',
            name='last_login_2',
            field=models.DateField(default=datetime.datetime(2023, 12, 14, 0, 0)),
        ),
        migrations.AlterField(
            model_name='indexeslaxoutuser',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 16, 10, 10, 19, 370870, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='indexesphysios',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 16, 10, 10, 19, 370870, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 16, 10, 10, 19, 371871, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='user_uid',
            field=models.CharField(default='615822a2-c29c-427e-acca-1822a9e55fce', max_length=420, unique=True),
        ),
    ]
