# Generated by Django 5.0 on 2023-12-16 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxout_app', '0018_doneworkouts_laxoutuser_last_login_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexeslaxoutuser',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 16, 10, 17, 11, 66621, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='indexesphysios',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 16, 10, 17, 11, 66621, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 16, 10, 17, 11, 67621, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='last_login_2',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 0, 0)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='user_uid',
            field=models.CharField(default='ae0fad10-8bae-479f-950e-8ae7ed1aef23', max_length=420, unique=True),
        ),
    ]
