# Generated by Django 5.0.2 on 2024-06-29 15:25

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "laxout_app",
            "0018_alter_doneexercises_date_alter_doneworkouts_date_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Befund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("befund", models.CharField(default="", max_length=200)),
                ("created_for", models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name="doneexercises",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 6, 29, 15, 25, 21, 926610)
            ),
        ),
        migrations.AlterField(
            model_name="doneworkouts",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 6, 29, 15, 25, 21, 926018)
            ),
        ),
        migrations.AlterField(
            model_name="indexesphysios",
            name="for_week",
            field=models.IntegerField(default=26),
        ),
        migrations.AlterField(
            model_name="laxoutuser",
            name="creation_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 6, 29, 15, 25, 21, 932845, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="laxoutuser",
            name="last_meet",
            field=models.DateField(
                default=datetime.datetime(2024, 6, 29, 15, 25, 21, 934646)
            ),
        ),
        migrations.AlterField(
            model_name="laxoutuserindexcreationlog",
            name="for_week",
            field=models.IntegerField(default=26),
        ),
        migrations.AlterField(
            model_name="laxoutuserpains",
            name="for_week",
            field=models.IntegerField(default=26),
        ),
        migrations.AlterField(
            model_name="physioindexcreationlog",
            name="for_week",
            field=models.IntegerField(default=26),
        ),
        migrations.CreateModel(
            name="AktiveBeweglichkeit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_for", models.IntegerField(default=0)),
                (
                    "created_at",
                    models.DateField(
                        default=datetime.datetime(2024, 6, 29, 15, 25, 21, 986816)
                    ),
                ),
                ("flexion_rechts_oB", models.BooleanField(default=False)),
                ("flexion_rechts_leicht_begrenzt", models.BooleanField(default=False)),
                (
                    "flexion_rechts_mittelgradig_begrenzt",
                    models.BooleanField(default=False),
                ),
                ("flexion_rechts_stark_begrenzt", models.BooleanField(default=False)),
                ("flexion_rechts_schmerzhaft", models.BooleanField(default=False)),
                ("flexion_rechts_gehemmt", models.BooleanField(default=False)),
                ("flexion_rechts_verzögert", models.BooleanField(default=False)),
                ("flexion_rechts_eingeschränkt", models.BooleanField(default=False)),
                ("flexion_rechts_unkoordiniert", models.BooleanField(default=False)),
                ("flexion_links_oB", models.BooleanField(default=False)),
                ("flexion_links_leicht_begrenzt", models.BooleanField(default=False)),
                (
                    "flexion_links_mittelgradig_begrenzt",
                    models.BooleanField(default=False),
                ),
                ("flexion_links_stark_begrenzt", models.BooleanField(default=False)),
                ("flexion_links_schmerzhaft", models.BooleanField(default=False)),
                ("flexion_links_gehemmt", models.BooleanField(default=False)),
                ("flexion_links_verzögert", models.BooleanField(default=False)),
                ("flexion_links_eingeschränkt", models.BooleanField(default=False)),
                ("flexion_links_unkoordiniert", models.BooleanField(default=False)),
                ("extension_rechts_oB", models.BooleanField(default=False)),
                (
                    "extension_rechts_leicht_begrenzt",
                    models.BooleanField(default=False),
                ),
                (
                    "extension_rechts_mittelgradig_begrenzt",
                    models.BooleanField(default=False),
                ),
                ("extension_rechts_stark_begrenzt", models.BooleanField(default=False)),
                ("extension_rechts_schmerzhaft", models.BooleanField(default=False)),
                ("extension_rechts_gehemmt", models.BooleanField(default=False)),
                ("extension_rechts_verzögert", models.BooleanField(default=False)),
                ("extension_rechts_eingeschränkt", models.BooleanField(default=False)),
                ("extension_rechts_unkoordiniert", models.BooleanField(default=False)),
                ("extension_links_oB", models.BooleanField(default=False)),
                ("extension_links_leicht_begrenzt", models.BooleanField(default=False)),
                (
                    "extension_links_mittelgradig_begrenzt",
                    models.BooleanField(default=False),
                ),
                ("extension_links_stark_begrenzt", models.BooleanField(default=False)),
                ("extension_links_schmerzhaft", models.BooleanField(default=False)),
                ("extension_links_gehemmt", models.BooleanField(default=False)),
                ("extension_links_verzögert", models.BooleanField(default=False)),
                ("extension_links_eingeschränkt", models.BooleanField(default=False)),
                ("extension_links_unkoordiniert", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Alltagsfunktionen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_for", models.IntegerField(default=0)),
                (
                    "created_at",
                    models.DateField(
                        default=datetime.datetime(2024, 6, 29, 15, 25, 22, 7791)
                    ),
                ),
                ("tiefe_hocke_ob", models.BooleanField(default=False)),
                ("tiefe_hocke_auffaellig", models.BooleanField(default=False)),
                ("tiefe_hocke_bemerkung", models.CharField(default="", max_length=755)),
                ("huepfen_einem_bein_ob", models.BooleanField(default=False)),
                ("huepfen_einem_bein_auffaellig", models.BooleanField(default=False)),
                (
                    "huepfen_einem_bein_bemerkung",
                    models.CharField(default="", max_length=755),
                ),
                ("ferstand_ob", models.BooleanField(default=False)),
                ("ferstand_auffaellig", models.BooleanField(default=False)),
                ("ferstand_bemerkung", models.CharField(default="", max_length=755)),
                ("fersenfall_ob", models.BooleanField(default=False)),
                ("fersenfall_auffaellig", models.BooleanField(default=False)),
                ("fersenfall_bemerkung", models.CharField(default="", max_length=755)),
                ("einbeinstand_ob", models.BooleanField(default=False)),
                ("einbeinstand_auffaellig", models.BooleanField(default=False)),
                (
                    "einbeinstand_bemerkung",
                    models.CharField(default="", max_length=755),
                ),
                ("treppe_ob", models.BooleanField(default=False)),
                ("treppe_auffaellig", models.BooleanField(default=False)),
                ("treppe_bemerkung", models.CharField(default="", max_length=755)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ApleyZeichen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_for", models.IntegerField(default=0)),
                (
                    "created_at",
                    models.DateField(
                        default=datetime.datetime(2024, 6, 29, 15, 25, 22, 31607)
                    ),
                ),
                ("ohne_befund", models.BooleanField(default=False)),
                ("positiv_auffaellig", models.BooleanField(default=False)),
                ("nicht_durchfuehrbar", models.BooleanField(default=False)),
                ("bemerkung", models.CharField(default="", max_length=755)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AprehensionTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_for", models.IntegerField(default=0)),
                (
                    "created_at",
                    models.DateField(
                        default=datetime.datetime(2024, 6, 29, 15, 25, 22, 17474)
                    ),
                ),
                ("ohne_befund", models.BooleanField(default=False)),
                ("positiv_auffaellig", models.BooleanField(default=False)),
                ("nicht_durchfuehrbar", models.BooleanField(default=False)),
                ("bemerkung", models.CharField(default="", max_length=755)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Beinlaengenmessung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_for", models.IntegerField(default=0)),
                (
                    "created_at",
                    models.DateField(
                        default=datetime.datetime(2024, 6, 29, 15, 25, 22, 9197)
                    ),
                ),
                ("anatomische_messung_rechts", models.IntegerField(default=0)),
                ("anatomische_messung_links", models.IntegerField(default=0)),
                ("funktionelle_messung_rechts", models.IntegerField(default=0)),
                ("funktionelle_messung_links", models.IntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BeweglichkeitsmessungKnie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_for", models.IntegerField(default=0)),
                (
                    "created_at",
                    models.DateField(
                        default=datetime.datetime(2024, 6, 29, 15, 25, 21, 999154)
                    ),
                ),
                (
                    "extension_flexion_rechts_value",
                    models.CharField(default="", max_length=100),
                ),
                (
                    "extension_flexion_links_value",
                    models.CharField(default="", max_length=100),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Einbeinstand30SekundenGeschlosseneAugen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_for", models.IntegerField(default=0)),
                (
                    "created_at",
                    models.DateField(
                        default=datetime.datetime(2024, 6, 29, 15, 25, 22, 7018)
                    ),
                ),
                ("oB", models.BooleanField(default=False)),
                ("kann_nicht_gehalten_werden", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Einbeinstand60Sekunden",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_for", models.IntegerField(default=0)),
                (
                    "created_at",
                    models.DateField(
                        default=datetime.datetime(2024, 6, 29, 15, 25, 22, 6230)
                    ),
                ),
                ("oB", models.BooleanField(default=False)),
                ("kann_nicht_gehalten_werden", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Facettendruckschmerztest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_for", models.IntegerField(default=0)),
                (
                    "created_at",
                    models.DateField(
                        default=datetime.datetime(2024, 6, 29, 15, 25, 22, 19257)
                    ),
                ),
                ("ohne_befund", models.BooleanField(default=False)),
                ("positiv_auffaellig", models.BooleanField(default=False)),
                ("nicht_durchfuehrbar", models.BooleanField(default=False)),
                ("bemerkung", models.CharField(default="", max_length=755)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FragenevaluationenNachDemBioPsychoSozialenKrankheitsmodell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_for", models.IntegerField(default=0)),
                (
                    "created_at",
                    models.DateField(
                        default=datetime.datetime(2024, 6, 29, 15, 25, 21, 973396)
                    ),
                ),
                (
                    "koerperliche_beschwerden",
                    models.CharField(default="", max_length=2000),
                ),
                (
                    "psychisch_gelagerte_eschwerden",
                    models.CharField(default="", max_length=2000),
                ),
                (
                    "probleme_mit_aktiver_teilhabe_am_sozialen_Leben",
                    models.CharField(default="", max_length=2000),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FragenevaluationenNachDen7WFragen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_for", models.IntegerField(default=0)),
                (
                    "created_at",
                    models.DateField(
                        default=datetime.datetime(2024, 6, 29, 15, 25, 21, 979579)
                    ),
                ),
                ("hauptbeschwerden", models.CharField(default="", max_length=2000)),
                ("lokalisierung", models.CharField(default="", max_length=2000)),
                ("provokation", models.CharField(default="", max_length=2000)),
                (
                    "orientierung_für_Maßnahmen",
                    models.CharField(default="", max_length=2000),
                ),
                ("schmerzqualität", models.CharField(default="", max_length=2000)),
                ("orientierung", models.CharField(default="", max_length=2000)),
                ("beschwerdeverlauf", models.CharField(default="", max_length=2000)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FragenevaluationNachICFKategorien",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_for", models.IntegerField(default=0)),
                (
                    "created_at",
                    models.DateField(
                        default=datetime.datetime(2024, 6, 29, 15, 25, 21, 972464)
                    ),
                ),
                (
                    "aktueller_gesundheitszustand",
                    models.CharField(default="", max_length=2000),
                ),
                ("struktur_funktion", models.CharField(default="", max_length=2000)),
                ("aktivitaet", models.CharField(default="", max_length=2000)),
                ("partizipation", models.CharField(default="", max_length=2000)),
                ("kontextfaktoren", models.CharField(default="", max_length=2000)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GlideTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_for", models.IntegerField(default=0)),
                (
                    "created_at",
                    models.DateField(
                        default=datetime.datetime(2024, 6, 29, 15, 25, 22, 15651)
                    ),
                ),
                ("ohne_befund", models.BooleanField(default=False)),
                ("positiv_auffaellig", models.BooleanField(default=False)),
                ("nicht_durchfuehrbar", models.BooleanField(default=False)),
                ("bemerkung", models.CharField(default="", max_length=755)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GravitiySign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_for", models.IntegerField(default=0)),
                (
                    "created_at",
                    models.DateField(
                        default=datetime.datetime(2024, 6, 29, 15, 25, 22, 25440)
                    ),
                ),
                ("ohne_befund", models.BooleanField(default=False)),
                ("positiv_auffaellig", models.BooleanField(default=False)),
                ("nicht_durchfuehrbar", models.BooleanField(default=False)),
                ("bemerkung", models.CharField(default="", max_length=755)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Hamstringtest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_for", models.IntegerField(default=0)),
                (
                    "created_at",
                    models.DateField(
                        default=datetime.datetime(2024, 6, 29, 15, 25, 22, 12033)
                    ),
                ),
                ("ohne_befund", models.BooleanField(default=False)),
                ("positiv_auffaellig", models.BooleanField(default=False)),
                ("nicht_durchfuehrbar", models.BooleanField(default=False)),
                ("bemerkung", models.CharField(default="", max_length=755)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HintereSchublade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_for", models.IntegerField(default=0)),
                (
                    "created_at",
                    models.DateField(
                        default=datetime.datetime(2024, 6, 29, 15, 25, 22, 24594)
                    ),
                ),
                ("ohne_befund", models.BooleanField(default=False)),
                ("positiv_auffaellig", models.BooleanField(default=False)),
                ("nicht_durchfuehrbar", models.BooleanField(default=False)),
                ("bemerkung", models.CharField(default="", max_length=755)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoriaMorbis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_for", models.IntegerField(default=0)),
                (
                    "created_at",
                    models.DateField(
                        default=datetime.datetime(2024, 6, 29, 15, 25, 21, 983094)
                    ),
                ),
                ("trauma_unfall", models.BooleanField(default=False)),
                ("atraumatisch", models.BooleanField(default=False)),
                ("chronisch", models.BooleanField(default=False)),
                ("progredient", models.BooleanField(default=False)),
                ("krankheitsverlauf", models.CharField(default="", max_length=2000)),
                (
                    "Krankenhausaufenthalte",
                    models.CharField(default="", max_length=2000),
                ),
                (
                    "unfaelle_verletzungen_operationen",
                    models.CharField(default="", max_length=2000),
                ),
                ("schwangerschaften", models.CharField(default="", max_length=2000)),
                (
                    "sucht_drogenverhalten",
                    models.CharField(default="", max_length=2000),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HughstonPlicaTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_for", models.IntegerField(default=0)),
                (
                    "created_at",
                    models.DateField(
                        default=datetime.datetime(2024, 6, 29, 15, 25, 22, 33432)
                    ),
                ),
                ("ohne_befund", models.BooleanField(default=False)),
                ("positiv_auffaellig", models.BooleanField(default=False)),
                ("nicht_durchfuehrbar", models.BooleanField(default=False)),
                ("bemerkung", models.CharField(default="", max_length=755)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IsometrischerKrafttest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_for", models.IntegerField(default=0)),
                (
                    "created_at",
                    models.DateField(
                        default=datetime.datetime(2024, 6, 29, 15, 25, 21, 999951)
                    ),
                ),
                ("flexion_oB", models.BooleanField(default=False)),
                (
                    "flexion_kann_nicht_gehalten_werden",
                    models.BooleanField(default=False),
                ),
                ("extension_oB", models.BooleanField(default=False)),
                (
                    "extension_kann_nicht_gehalten_werden",
                    models.BooleanField(default=False),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LachmannTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_for", models.IntegerField(default=0)),
                (
                    "created_at",
                    models.DateField(
                        default=datetime.datetime(2024, 6, 29, 15, 25, 22, 21982)
                    ),
                ),
                ("ohne_befund", models.BooleanField(default=False)),
                ("positiv_auffaellig", models.BooleanField(default=False)),
                ("nicht_durchfuehrbar", models.BooleanField(default=False)),
                ("bemerkung", models.CharField(default="", max_length=755)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LoomersTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_for", models.IntegerField(default=0)),
                (
                    "created_at",
                    models.DateField(
                        default=datetime.datetime(2024, 6, 29, 15, 25, 22, 26397)
                    ),
                ),
                ("ohne_befund", models.BooleanField(default=False)),
                ("positiv_auffaellig", models.BooleanField(default=False)),
                ("nicht_durchfuehrbar", models.BooleanField(default=False)),
                ("bemerkung", models.CharField(default="", max_length=755)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MacMurrayTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_for", models.IntegerField(default=0)),
                (
                    "created_at",
                    models.DateField(
                        default=datetime.datetime(2024, 6, 29, 15, 25, 22, 29946)
                    ),
                ),
                ("ohne_befund", models.BooleanField(default=False)),
                ("positiv_auffaellig", models.BooleanField(default=False)),
                ("nicht_durchfuehrbar", models.BooleanField(default=False)),
                ("bemerkung", models.CharField(default="", max_length=755)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedioPatellarerPlicaTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_for", models.IntegerField(default=0)),
                (
                    "created_at",
                    models.DateField(
                        default=datetime.datetime(2024, 6, 29, 15, 25, 22, 32561)
                    ),
                ),
                ("ohne_befund", models.BooleanField(default=False)),
                ("positiv_auffaellig", models.BooleanField(default=False)),
                ("nicht_durchfuehrbar", models.BooleanField(default=False)),
                ("bemerkung", models.CharField(default="", max_length=755)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MiniErgussTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_for", models.IntegerField(default=0)),
                (
                    "created_at",
                    models.DateField(
                        default=datetime.datetime(2024, 6, 29, 15, 25, 22, 14799)
                    ),
                ),
                ("ohne_befund", models.BooleanField(default=False)),
                ("positiv_auffaellig", models.BooleanField(default=False)),
                ("nicht_durchfuehrbar", models.BooleanField(default=False)),
                ("bemerkung", models.CharField(default="", max_length=755)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MRectusDehnungstest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_for", models.IntegerField(default=0)),
                (
                    "created_at",
                    models.DateField(
                        default=datetime.datetime(2024, 6, 29, 15, 25, 22, 11096)
                    ),
                ),
                ("ohne_befund", models.BooleanField(default=False)),
                ("positiv_auffaellig", models.BooleanField(default=False)),
                ("nicht_durchfuehrbar", models.BooleanField(default=False)),
                ("bemerkung", models.CharField(default="", max_length=755)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Muskelfunktionspruefung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_for", models.IntegerField(default=0)),
                (
                    "created_at",
                    models.DateField(
                        default=datetime.datetime(2024, 6, 29, 15, 25, 22, 774)
                    ),
                ),
                ("flexion_1", models.BooleanField(default=False)),
                ("flexion_2", models.BooleanField(default=False)),
                ("flexion_3", models.BooleanField(default=False)),
                ("flexion_4", models.BooleanField(default=False)),
                ("flexion_5", models.BooleanField(default=False)),
                ("extension_1", models.BooleanField(default=False)),
                ("extension_2", models.BooleanField(default=False)),
                ("extension_3", models.BooleanField(default=False)),
                ("extension_4", models.BooleanField(default=False)),
                ("extension_5", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NebenerkrankungenMedikamente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_for", models.IntegerField(default=0)),
                (
                    "created_at",
                    models.DateField(
                        default=datetime.datetime(2024, 6, 29, 15, 25, 21, 981483)
                    ),
                ),
                ("erbkrankheiten", models.BooleanField(default=False)),
                (
                    "erbkrankheiten_krankheit",
                    models.CharField(default="", max_length=1000),
                ),
                (
                    "erbkrankheiten_medikamente",
                    models.CharField(default="", max_length=1000),
                ),
                ("metabolische_erkrankungen", models.BooleanField(default=False)),
                (
                    "metabolische_erkrankungen_krankheit",
                    models.CharField(default="", max_length=1000),
                ),
                (
                    "metabolische_erkrankungen_medikamente",
                    models.CharField(default="", max_length=1000),
                ),
                ("psychische_erkrankungen", models.BooleanField(default=False)),
                (
                    "psychische_erkrankungen_krankheit",
                    models.CharField(default="", max_length=1000),
                ),
                (
                    "psychische_erkrankungen_medikamente",
                    models.CharField(default="", max_length=1000),
                ),
                ("herz_kreislauferkrankungen", models.BooleanField(default=False)),
                (
                    "herz_kreislauferkrankungen_krankheit",
                    models.CharField(default="", max_length=1000),
                ),
                (
                    "herz_kreislauferkrankungen_medikamente",
                    models.CharField(default="", max_length=1000),
                ),
                ("neurologische_erkrankungen", models.BooleanField(default=False)),
                (
                    "neurologische_erkrankungen_krankheit",
                    models.CharField(default="", max_length=1000),
                ),
                (
                    "neurologische_erkrankungen_medikamente",
                    models.CharField(default="", max_length=1000),
                ),
                (
                    "rheumatisch_entzuendliche_erkrankungen",
                    models.BooleanField(default=False),
                ),
                (
                    "rheumatisch_entzuendliche_erkrankungen_krankheit",
                    models.CharField(default="", max_length=1000),
                ),
                (
                    "rheumatisch_entzuendliche_erkrankungen_medikamente",
                    models.CharField(default="", max_length=1000),
                ),
                ("erkrankungen_bewegungsapparat", models.BooleanField(default=False)),
                (
                    "erkrankungen_bewegungsapparat_erkrankungen_krankheit",
                    models.CharField(default="", max_length=1000),
                ),
                (
                    "erkrankungen_bewegungsapparat_erkrankungen_medikamente",
                    models.CharField(default="", max_length=1000),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NrsNumericRatingScale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_for", models.IntegerField(default=0)),
                (
                    "created_at",
                    models.DateField(
                        default=datetime.datetime(2024, 6, 29, 15, 25, 21, 985778)
                    ),
                ),
                ("kein_schmerz", models.BooleanField(default=False)),
                ("sanft", models.BooleanField(default=False)),
                ("gering", models.BooleanField(default=False)),
                ("unbequem", models.BooleanField(default=False)),
                ("mittelgradig", models.BooleanField(default=False)),
                ("ablenkend", models.BooleanField(default=False)),
                ("quaelend", models.BooleanField(default=False)),
                ("starker_schmerz", models.BooleanField(default=False)),
                ("hochgradiger_schmerz", models.BooleanField(default=False)),
                ("unertraeglich", models.BooleanField(default=False)),
                ("unbeschreiblich", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PassiveBeweglichkeit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_for", models.IntegerField(default=0)),
                (
                    "created_at",
                    models.DateField(
                        default=datetime.datetime(2024, 6, 29, 15, 25, 21, 988810)
                    ),
                ),
                ("flexion_rechts_oB", models.BooleanField(default=False)),
                ("flexion_rechts_leicht_begrenzt", models.BooleanField(default=False)),
                (
                    "flexion_rechts_mittelgradig_begrenzt",
                    models.BooleanField(default=False),
                ),
                ("flexion_rechts_stark_begrenzt", models.BooleanField(default=False)),
                (
                    "flexion_rechts_fest_elastischer_stopp",
                    models.BooleanField(default=False),
                ),
                (
                    "flexion_rechts_weich_elastischer_stopp",
                    models.BooleanField(default=False),
                ),
                (
                    "flexion_rechts_hart_unelastischer_stopp",
                    models.BooleanField(default=False),
                ),
                (
                    "flexion_rechts_fester_unelastischer_stopp",
                    models.BooleanField(default=False),
                ),
                (
                    "flexion_rechts_fester_elastischer_stopp",
                    models.BooleanField(default=False),
                ),
                (
                    "flexion_rechts_leeres_endgefuehl",
                    models.BooleanField(default=False),
                ),
                ("flexion_rechts_schmerz", models.BooleanField(default=False)),
                ("flexion_links_oB", models.BooleanField(default=False)),
                ("flexion_links_leicht_begrenzt", models.BooleanField(default=False)),
                (
                    "flexion_links_mittelgradig_begrenzt",
                    models.BooleanField(default=False),
                ),
                ("flexion_links_stark_begrenzt", models.BooleanField(default=False)),
                (
                    "flexion_links_fest_elastischer_stopp",
                    models.BooleanField(default=False),
                ),
                (
                    "flexion_links_weich_elastischer_stopp",
                    models.BooleanField(default=False),
                ),
                (
                    "flexion_links_hart_unelastischer_stopp",
                    models.BooleanField(default=False),
                ),
                (
                    "flexion_links_fester_unelastischer_stopp",
                    models.BooleanField(default=False),
                ),
                (
                    "flexion_links_fester_elastischer_stopp",
                    models.BooleanField(default=False),
                ),
                ("flexion_links_leeres_endgefuehl", models.BooleanField(default=False)),
                ("flexion_links_schmerz", models.BooleanField(default=False)),
                ("extension_rechts_oB", models.BooleanField(default=False)),
                (
                    "extension_rechts_leicht_begrenzt",
                    models.BooleanField(default=False),
                ),
                (
                    "extension_rechts_mittelgradig_begrenztb",
                    models.BooleanField(default=False),
                ),
                ("extension_rechts_stark_begrenzt", models.BooleanField(default=False)),
                (
                    "extension_rechts_fest_elastischer_stopp",
                    models.BooleanField(default=False),
                ),
                (
                    "extension_rechts_weich_elastischer_stopp",
                    models.BooleanField(default=False),
                ),
                (
                    "extension_rechts_hart_unelastischer_stopp",
                    models.BooleanField(default=False),
                ),
                (
                    "extension_rechts_fester_unelastischer_stopp",
                    models.BooleanField(default=False),
                ),
                (
                    "extension_rechts_fester_elastischer_stopp",
                    models.BooleanField(default=False),
                ),
                (
                    "extension_rechts_leeres_endgefuehl",
                    models.BooleanField(default=False),
                ),
                ("extension_rechts_schmerz", models.BooleanField(default=False)),
                ("extension_links_oB", models.BooleanField(default=False)),
                ("extension_links_leicht_begrenzt", models.BooleanField(default=False)),
                (
                    "extension_links_mittelgradig_begrenzt",
                    models.BooleanField(default=False),
                ),
                ("extension_links_stark_begrenzt", models.BooleanField(default=False)),
                (
                    "extension_links_fest_elastischer_stopp",
                    models.BooleanField(default=False),
                ),
                (
                    "extension_links_weich_elastischer_stopp",
                    models.BooleanField(default=False),
                ),
                (
                    "extension_links_hart_unelastischer_stopp",
                    models.BooleanField(default=False),
                ),
                (
                    "extension_links_fester_unelastischer_stopp",
                    models.BooleanField(default=False),
                ),
                (
                    "extension_links_fester_elastischer_stopp",
                    models.BooleanField(default=False),
                ),
                (
                    "extension_links_leeres_endgefuehl",
                    models.BooleanField(default=False),
                ),
                ("extension_links_schmerz", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PayrZeichen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_for", models.IntegerField(default=0)),
                (
                    "created_at",
                    models.DateField(
                        default=datetime.datetime(2024, 6, 29, 15, 25, 22, 30768)
                    ),
                ),
                ("ohne_befund", models.BooleanField(default=False)),
                ("positiv_auffaellig", models.BooleanField(default=False)),
                ("nicht_durchfuehrbar", models.BooleanField(default=False)),
                ("bemerkung", models.CharField(default="", max_length=755)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PivotShiftTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_for", models.IntegerField(default=0)),
                (
                    "created_at",
                    models.DateField(
                        default=datetime.datetime(2024, 6, 29, 15, 25, 22, 23722)
                    ),
                ),
                ("ohne_befund", models.BooleanField(default=False)),
                ("positiv_auffaellig", models.BooleanField(default=False)),
                ("nicht_durchfuehrbar", models.BooleanField(default=False)),
                ("bemerkung", models.CharField(default="", max_length=755)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuadricepsDehnungstest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_for", models.IntegerField(default=0)),
                (
                    "created_at",
                    models.DateField(
                        default=datetime.datetime(2024, 6, 29, 15, 25, 22, 10065)
                    ),
                ),
                ("ohne_befund", models.BooleanField(default=False)),
                ("positiv_auffaellig", models.BooleanField(default=False)),
                ("nicht_durchfuehrbar", models.BooleanField(default=False)),
                ("bemerkung", models.CharField(default="", max_length=755)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StandartBefund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_for", models.IntegerField(default=0)),
                (
                    "created_at",
                    models.DateField(
                        default=datetime.datetime(2024, 6, 29, 15, 25, 21, 984313)
                    ),
                ),
                ("name", models.CharField(default="", max_length=50)),
                ("vorname", models.CharField(default="", max_length=50)),
                ("alter", models.IntegerField(default=0)),
                ("diagnose", models.CharField(default="", max_length=1000)),
                ("hauptziel", models.CharField(default="", max_length=2000)),
                ("vollbelastung", models.BooleanField(default=False)),
                ("teilbeslastung", models.BooleanField(default=False)),
                ("lagerungstabil", models.BooleanField(default=False)),
                ("maximalpuls", models.BooleanField(default=False)),
                (
                    "therapeutische_ziele_maßnahmen",
                    models.CharField(default="", max_length=2000),
                ),
                ("op_vorliegend", models.BooleanField(default=False)),
                ("medikament_einnahme", models.BooleanField(default=False)),
                ("geschlecht", models.CharField(default="", max_length=100)),
                ("groeße", models.IntegerField(default=0)),
                ("gewicht", models.IntegerField(default=0)),
                ("konstitutionstyp", models.CharField(default="", max_length=1000)),
                ("beruf", models.CharField(default="", max_length=500)),
                ("alltagsaktivitaeten", models.CharField(default="", max_length=500)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StandDerReHaPhase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_for", models.IntegerField(default=0)),
                (
                    "created_at",
                    models.DateField(
                        default=datetime.datetime(2024, 6, 29, 15, 25, 21, 980604)
                    ),
                ),
                ("akute_phase", models.BooleanField(default=False)),
                ("wundheilungsphase", models.BooleanField(default=False)),
                ("frueh_phase_ReHa", models.BooleanField(default=False)),
                ("mittlere_phase_Reha", models.BooleanField(default=False)),
                ("spaet_phase_reha", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Steinmann1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_for", models.IntegerField(default=0)),
                (
                    "created_at",
                    models.DateField(
                        default=datetime.datetime(2024, 6, 29, 15, 25, 22, 27390)
                    ),
                ),
                ("ohne_befund", models.BooleanField(default=False)),
                ("positiv_auffaellig", models.BooleanField(default=False)),
                ("nicht_durchfuehrbar", models.BooleanField(default=False)),
                ("bemerkung", models.CharField(default="", max_length=755)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Steinmann3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_for", models.IntegerField(default=0)),
                (
                    "created_at",
                    models.DateField(
                        default=datetime.datetime(2024, 6, 29, 15, 25, 22, 28225)
                    ),
                ),
                ("ohne_befund", models.BooleanField(default=False)),
                ("positiv_auffaellig", models.BooleanField(default=False)),
                ("nicht_durchfuehrbar", models.BooleanField(default=False)),
                ("bemerkung", models.CharField(default="", max_length=755)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TanzendePatella",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_for", models.IntegerField(default=0)),
                (
                    "created_at",
                    models.DateField(
                        default=datetime.datetime(2024, 6, 29, 15, 25, 22, 13938)
                    ),
                ),
                ("ohne_befund", models.BooleanField(default=False)),
                ("positiv_auffaellig", models.BooleanField(default=False)),
                ("nicht_durchfuehrbar", models.BooleanField(default=False)),
                ("bemerkung", models.CharField(default="", max_length=755)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TheslayTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_for", models.IntegerField(default=0)),
                (
                    "created_at",
                    models.DateField(
                        default=datetime.datetime(2024, 6, 29, 15, 25, 22, 29034)
                    ),
                ),
                ("ohne_befund", models.BooleanField(default=False)),
                ("positiv_auffaellig", models.BooleanField(default=False)),
                ("nicht_durchfuehrbar", models.BooleanField(default=False)),
                ("bemerkung", models.CharField(default="", max_length=755)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TiltTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_for", models.IntegerField(default=0)),
                (
                    "created_at",
                    models.DateField(
                        default=datetime.datetime(2024, 6, 29, 15, 25, 22, 16612)
                    ),
                ),
                ("ohne_befund", models.BooleanField(default=False)),
                ("positiv_auffaellig", models.BooleanField(default=False)),
                ("nicht_durchfuehrbar", models.BooleanField(default=False)),
                ("bemerkung", models.CharField(default="", max_length=755)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Umfangsmessung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_for", models.IntegerField(default=0)),
                (
                    "created_at",
                    models.DateField(
                        default=datetime.datetime(2024, 6, 29, 15, 25, 22, 12892)
                    ),
                ),
                (
                    "messort_10cm_oberhalb_kniegelenkspalt_rechts",
                    models.IntegerField(default=0),
                ),
                (
                    "messort_10cm_oberhalb_kniegelenkspalt_links",
                    models.IntegerField(default=0),
                ),
                ("messort_am_kniegelenkspalt_rechts", models.IntegerField(default=0)),
                ("messort_am_kniegelenkspalt_links", models.IntegerField(default=0)),
                (
                    "messort_10cm_unterhalb_kniegelenkspalt_rechts",
                    models.IntegerField(default=0),
                ),
                (
                    "messort_10cm_unterhalb_kniegelenkspalt_links",
                    models.IntegerField(default=0),
                ),
                (
                    "messort_15cm_unterhalb_kniegelenkspalt_rechts",
                    models.IntegerField(default=0),
                ),
                (
                    "messort_15cm_unterhalb_kniegelenkspalt_links",
                    models.IntegerField(default=0),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ValgusTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_for", models.IntegerField(default=0)),
                (
                    "created_at",
                    models.DateField(
                        default=datetime.datetime(2024, 6, 29, 15, 25, 22, 20127)
                    ),
                ),
                ("ohne_befund", models.BooleanField(default=False)),
                ("positiv_auffaellig", models.BooleanField(default=False)),
                ("nicht_durchfuehrbar", models.BooleanField(default=False)),
                ("bemerkung", models.CharField(default="", max_length=755)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VarusTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_for", models.IntegerField(default=0)),
                (
                    "created_at",
                    models.DateField(
                        default=datetime.datetime(2024, 6, 29, 15, 25, 22, 20998)
                    ),
                ),
                ("ohne_befund", models.BooleanField(default=False)),
                ("positiv_auffaellig", models.BooleanField(default=False)),
                ("nicht_durchfuehrbar", models.BooleanField(default=False)),
                ("bemerkung", models.CharField(default="", max_length=755)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VordereSchublade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_for", models.IntegerField(default=0)),
                (
                    "created_at",
                    models.DateField(
                        default=datetime.datetime(2024, 6, 29, 15, 25, 22, 22853)
                    ),
                ),
                ("ohne_befund", models.BooleanField(default=False)),
                ("positiv_auffaellig", models.BooleanField(default=False)),
                ("nicht_durchfuehrbar", models.BooleanField(default=False)),
                ("bemerkung", models.CharField(default="", max_length=755)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ZohlenZeichen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_for", models.IntegerField(default=0)),
                (
                    "created_at",
                    models.DateField(
                        default=datetime.datetime(2024, 6, 29, 15, 25, 22, 18379)
                    ),
                ),
                ("ohne_befund", models.BooleanField(default=False)),
                ("positiv_auffaellig", models.BooleanField(default=False)),
                ("nicht_durchfuehrbar", models.BooleanField(default=False)),
                ("bemerkung", models.CharField(default="", max_length=755)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
