# Generated by Django 5.0 on 2023-12-16 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxout_app', '0020_remove_indexesphysios_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexeslaxoutuser',
            name='creation_date',
            field=models.DateField(default=12),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 16, 17, 5, 7, 608630, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='user_uid',
            field=models.CharField(default='f934b13a-4fd9-4a8d-a82f-6cad21fb5886', max_length=420, unique=True),
        ),
    ]
