# Generated by Django 5.0 on 2023-12-16 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxout_app', '0021_alter_indexeslaxoutuser_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexeslaxoutuser',
            name='creation_date',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 16, 17, 6, 49, 966446, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='user_uid',
            field=models.CharField(default='2f37e8d4-22d1-402e-97b5-d8ce643de2a2', max_length=420, unique=True),
        ),
    ]
