# Generated by Django 5.0 on 2023-12-17 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxout_app', '0022_alter_indexeslaxoutuser_creation_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indexesphysios',
            old_name='index',
            new_name='indexs',
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 17, 9, 21, 2, 627377, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 14, 0, 0)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='last_login_2',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 14, 0, 0)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='user_uid',
            field=models.CharField(default='da5103a8-eab8-48c6-a2bc-6c28413fe590', max_length=420, unique=True),
        ),
    ]
