# Generated by Django 5.0 on 2023-12-17 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laxout_app', '0024_indexesphysios_nine_ten_indexesphysios_six_eight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='average_pain',
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 17, 16, 24, 50, 968675, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='laxoutuser',
            name='user_uid',
            field=models.CharField(default='cc243382-7e12-4ee3-9435-9f81527dc027', max_length=420, unique=True),
        ),
        migrations.DeleteModel(
            name='Pains',
        ),
    ]
